kotlin.code.style=official
kotlin.stdlib.default.dependency=false

org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.242
loader_version_range=[5.12,)

kotlin_version=2.4.0
kotlin_for_forge_version=5.12.0
ldlib2_version=2.2.29
ldlib2_version_range=[2.2.29,2.3.0)
jei_version=19.39.0.369
jade_version=15.10.5+neoforge
fzzy_config_version=0.7.2+1.21+neoforge
fzzy_config_version_range=[0.7.2,0.8.0)
curios_version=9.5.1+1.21.1
curios_version_range=[9.5.1+1.21.1,10.0.0)
silent_gear_version=4.2.1.1
silent_gear_version_range=[4.2.1.1,4.3.0)
silent_lib_version=10.6.0

mod_id=lazy
mod_name=Lazy
mod_license=All Rights Reserved
mod_version=0.2.2
mod_group_id=rhx.lazy
mod_authors=Rhynia
mod_description=A lazy utility toolbox for Minecraft.
